task: pinn_basic
exp_name: pinn_basic
net_name: gabor
# net_name: mlp
tensorboard_root: "/PINNgabor/exp/tensorboard/"
# task_type: test
task_type: train
loss_type: implicit

results_path: results/${net_name}/${exp_name}-${now:%Y-%m-%d-%H-%M-%S.%fZ}/
checkpoint_path: ${results_path}/checkpoints/
visualize_path: ${results_path}/vis/ # set it None to skip vis
#visualize_path: None # set it None to skip vis
code_path: ${results_path}/code/
tensorboard_path: results/tb/${exp_name}-${net_name}-${now:%Y-%m-%d-%H-%M-%S.%fZ}

defaults:
  - _self_
  - pinn: pinn_basic

hydra:
  run:
    dir: /PINNgabor/exp/
